#!/usr/bin/env bash

if [[ -e ~/.birth ]]; then
	let BIRTH=$(<~/.birth)
else
	let BIRTH=19710311
fi
let NOW=`date +%Y%m%d`
let DIFF=(`date +%s -d $NOW`-`date +%s -d $BIRTH`)/86400

echo "$DIFF day's left since your birth date"
