#!/usr/bin/env bash

function check_opts() {
  while getopts ":b:" opt; do
    case $opt in
      b)
        BIRTH=$OPTARG;
        echo $BIRTH > ~/.birth;
        ;;
      \?)
        echo "Invalid option: -$OPTARG" >&2
        exit 1
        ;;
      :)
        echo "Option -$OPTARG requires an argument." >&2
        exit 1
        ;;
    esac
  done

  shift $((OPTIND -1))
}

function get_birth() {
  if [[ -e ~/.birth ]]; then
    let BIRTH=$(<~/.birth)
  else
    let BIRTH=19710311
  fi
}

function calculate_birth() {
  let NOW=`date +%Y%m%d`
  let DIFF=(`date +%s -d $NOW`-`date +%s -d $BIRTH`)/86400 
}

function user_output() {
  bold=$(tput bold)
  echo -e "You are \e[40m\033[1m\e[93m$DIFF\033[0m days old."
}

function main() {
  check_opts "$@"

  get_birth

  calculate_birth
  
  user_output
}


main "$@"
